apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
namespace: argo-app
images:
- name: argo-app
  newName: akshit8/argo-app
  newTag: 51e15506b7e5d57e1a68bacffa986bb431263ab5
