apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
namespace: argo-app
images:
- name: argo-app
  newName: akshit8/argo-app
  newTag: 9f0d1624c21656b4bbf2ae9bf8597c0d009a06b8
