apiVersion: v1
kind: Service
metadata:
  labels:
    app: argo-app
  name: argo-app
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: argo-app
  type: NodePort