apiVersion: v1
kind: Service
metadata:
  labels:
    app: argo-app
  name: argo-app
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: argo-app
  type: NodePort